"""
Engine-owned read models (tables).

These tables store engine outputs:
- Alerts
- Suggestions
- Computed insights

Engines write to these tables. Verticals ONLY read from them via API.
All tables are multi-tenant with vertical isolation.
"""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import Column, DateTime, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.ext.declarative import declarative_base

EngineBase = declarative_base()


class EngineModelMixin:
    """Common fields for all engine models."""

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)
    tenant_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    vertical = Column(String(50), nullable=False, default="materials", index=True)
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)


class EngineStockAlert(EngineBase, EngineModelMixin):
    """
    Stock alerts generated by Stock Intelligence Engine.

    Alerts for:
    - Rupture risk (stock below minimum)
    - Excess stock
    """

    __tablename__ = "engine_stock_alerts"

    product_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False)  # "rupture", "excess"
    risk_level = Column(String(20), nullable=False)  # "alto", "medio", "baixo"
    current_stock = Column(String(50), nullable=False)  # Stored as string for precision
    minimum_stock = Column(String(50), nullable=False)
    days_until_rupture = Column(String(20), nullable=True)
    explanation = Column(Text, nullable=True)
    payload = Column(JSONB, nullable=False, default=dict)
    status = Column(String(20), nullable=False, default="active")  # "active", "acknowledged", "resolved"

    __table_args__ = (
        Index("idx_stock_alerts_tenant_product", "tenant_id", "product_id"),
        Index("idx_stock_alerts_tenant_status", "tenant_id", "status"),
    )


class EngineReplenishmentSuggestion(EngineBase, EngineModelMixin):
    """
    Replenishment suggestions generated by Stock Intelligence Engine.
    """

    __tablename__ = "engine_replenishment_suggestions"

    product_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    suggested_quantity = Column(String(50), nullable=False)
    current_stock = Column(String(50), nullable=False)
    minimum_stock = Column(String(50), nullable=False)
    maximum_stock = Column(String(50), nullable=False)
    priority = Column(String(20), nullable=False)  # "alta", "media", "baixa"
    explanation = Column(Text, nullable=True)
    payload = Column(JSONB, nullable=False, default=dict)
    status = Column(String(20), nullable=False, default="pending")  # "pending", "accepted", "rejected"

    __table_args__ = (
        Index("idx_replenishment_tenant_product", "tenant_id", "product_id"),
        Index("idx_replenishment_tenant_status", "tenant_id", "status"),
    )


class EngineSalesSuggestion(EngineBase, EngineModelMixin):
    """
    Sales suggestions generated by Sales Intelligence Engine.

    Suggestions for:
    - Complementary products
    - Substitute products
    - Bundles
    """

    __tablename__ = "engine_sales_suggestions"

    suggestion_type = Column(String(50), nullable=False)  # "complementary", "substitute", "bundle"
    source_product_id = Column(PGUUID(as_uuid=True), nullable=True, index=True)
    suggested_product_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    frequency = Column(String(20), nullable=True)  # Percentage
    priority = Column(String(20), nullable=False)  # "alta", "media", "baixa"
    explanation = Column(Text, nullable=True)
    payload = Column(JSONB, nullable=False, default=dict)
    status = Column(String(20), nullable=False, default="active")

    __table_args__ = (
        Index("idx_sales_suggestions_tenant_source", "tenant_id", "source_product_id"),
        Index("idx_sales_suggestions_tenant_type", "tenant_id", "suggestion_type"),
    )


class EngineSupplierPriceAlert(EngineBase, EngineModelMixin):
    """
    Supplier price alerts generated by Pricing & Supplier Intelligence Engine.
    """

    __tablename__ = "engine_supplier_price_alerts"

    product_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    supplier_id = Column(PGUUID(as_uuid=True), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False)  # "price_increase", "price_decrease", "best_price"
    current_price = Column(String(50), nullable=False)
    reference_price = Column(String(50), nullable=True)
    price_change_percent = Column(String(20), nullable=True)
    explanation = Column(Text, nullable=True)
    payload = Column(JSONB, nullable=False, default=dict)
    status = Column(String(20), nullable=False, default="active")

    __table_args__ = (
        Index("idx_supplier_alerts_tenant_product", "tenant_id", "product_id"),
        Index("idx_supplier_alerts_tenant_supplier", "tenant_id", "supplier_id"),
    )


class EngineDeliveryRoute(EngineBase, EngineModelMixin):
    """
    Delivery routes generated by Delivery & Fulfillment Engine.
    """

    __tablename__ = "engine_delivery_routes"

    route_date = Column(DateTime(timezone=True), nullable=False)
    route_name = Column(String(200), nullable=True)
    total_orders = Column(String(10), nullable=False)
    total_distance_km = Column(String(20), nullable=True)
    estimated_duration_minutes = Column(String(20), nullable=True)
    order_ids = Column(JSONB, nullable=False)  # List of order IDs
    route_sequence = Column(JSONB, nullable=False)  # Ordered list of stops
    explanation = Column(Text, nullable=True)
    payload = Column(JSONB, nullable=False, default=dict)
    status = Column(String(20), nullable=False, default="planned")  # "planned", "in_progress", "completed"

    __table_args__ = (
        Index("idx_delivery_routes_tenant_date", "tenant_id", "route_date"),
        Index("idx_delivery_routes_tenant_status", "tenant_id", "status"),
    )

